version: "3.7"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ../code:/usr/share/nginx/
    links:
      - php
  php:
    container_name: php7
    image: php:fpm-alpine
    ports:
      - "9000:9000"
    volumes:
      - ../code:/usr/share/nginx/
